export const aboutImages = {
  hero: "/images/about/hero.jpg",
  heroBg: "/images/about/hero/bg.png",
  heroGlobe: "/images/about/hero/globe.png",
  workGlow: "/images/about/what/glow.svg",
  workRings: "/images/about/what/rings.svg",
  workGlowStories: "/images/about/what/glow-stories.svg",
  workGlowAmbassadors: "/images/about/what/glow-ambassadors.svg",
  iconPin: "/images/about/what/icon-pin.svg",
  iconUser: "/images/about/what/icon-user.svg",
  iconCrosshair: "/images/about/what/icon-crosshair.svg",
  avatar1: "/images/about/what/avatar-1.png",
  avatar2: "/images/about/what/avatar-2.png",
  avatar3: "/images/about/what/avatar-3.png",
  pavilionPin: "/images/about/what/pin-photo.png",
  homeSlide: "/images/about/home-slide.jpg",
  youth: "/images/about/youth.jpg",
  youthBg: "/images/about/youth-bg.png",
  partnerCard: "/images/about/partner-card.png",
  partnersGlow: "/images/about/partners-glow.svg",
  arrowUp: "/images/about/arrow-up.svg",
} as const;

export const aboutTeamPhotos = [
  "/images/about/team-01.png",
  "/images/about/team-02.png",
  "/images/about/team-03.png",
  "/images/about/team-04.png",
  "/images/about/team-05.png",
  "/images/about/team-06.png",
  "/images/about/team-07.png",
  "/images/about/team-08.png",
  "/images/about/team-09.png",
  "/images/about/team-10.png",
  "/images/about/team-11.png",
  "/images/about/team-12.png",
  "/images/about/team-13.png",
  "/images/about/team-14.png",
  "/images/about/team-15.png",
  "/images/about/team-16.png",
  "/images/about/team-17.png",
  "/images/about/team-18.png",
  "/images/about/team-19.png",
  "/images/about/team-20.png",
  "/images/about/team-21.png",
] as const;
