// Country list for the application form's nationality / based-in / phone-code
// pickers. Emoji flags render at text size, so no flag assets are needed.
export type Country = { name: string; flag: string; dial: string };

export const COUNTRIES: Country[] = [
  { name: "United States of America", flag: "🇺🇸", dial: "+1" },
  { name: "Germany", flag: "🇩🇪", dial: "+49" },
  { name: "Australia", flag: "🇦🇺", dial: "+61" },
  { name: "Japan", flag: "🇯🇵", dial: "+81" },
  { name: "Canada", flag: "🇨🇦", dial: "+1" },
  { name: "Brazil", flag: "🇧🇷", dial: "+55" },
  { name: "Ghana", flag: "🇬🇭", dial: "+233" },
  { name: "Nigeria", flag: "🇳🇬", dial: "+234" },
  { name: "Kenya", flag: "🇰🇪", dial: "+254" },
  { name: "South Africa", flag: "🇿🇦", dial: "+27" },
  { name: "Egypt", flag: "🇪🇬", dial: "+20" },
  { name: "Morocco", flag: "🇲🇦", dial: "+212" },
  { name: "Ethiopia", flag: "🇪🇹", dial: "+251" },
  { name: "Tanzania", flag: "🇹🇿", dial: "+255" },
  { name: "Uganda", flag: "🇺🇬", dial: "+256" },
  { name: "Senegal", flag: "🇸🇳", dial: "+221" },
  { name: "Côte d'Ivoire", flag: "🇨🇮", dial: "+225" },
  { name: "Cameroon", flag: "🇨🇲", dial: "+237" },
  { name: "Rwanda", flag: "🇷🇼", dial: "+250" },
  { name: "United Kingdom", flag: "🇬🇧", dial: "+44" },
  { name: "France", flag: "🇫🇷", dial: "+33" },
  { name: "Netherlands", flag: "🇳🇱", dial: "+31" },
  { name: "Spain", flag: "🇪🇸", dial: "+34" },
  { name: "Italy", flag: "🇮🇹", dial: "+39" },
  { name: "Turkey", flag: "🇹🇷", dial: "+90" },
  { name: "India", flag: "🇮🇳", dial: "+91" },
  { name: "Pakistan", flag: "🇵🇰", dial: "+92" },
  { name: "Bangladesh", flag: "🇧🇩", dial: "+880" },
  { name: "Indonesia", flag: "🇮🇩", dial: "+62" },
  { name: "Philippines", flag: "🇵🇭", dial: "+63" },
  { name: "Mexico", flag: "🇲🇽", dial: "+52" },
  { name: "Argentina", flag: "🇦🇷", dial: "+54" },
  { name: "Colombia", flag: "🇨🇴", dial: "+57" },
  { name: "United Arab Emirates", flag: "🇦🇪", dial: "+971" },
  { name: "Saudi Arabia", flag: "🇸🇦", dial: "+966" },
  { name: "China", flag: "🇨🇳", dial: "+86" },
  { name: "Other", flag: "🌍", dial: "+" },
];
