export const partnerImages = {
  hero: "/images/partner/hero-photo.jpg",
  heroPhoto: "/images/partner/hero-photo.jpg",
  heroUnion: "/images/partner/hero-union.png",
  logoMark: "/images/partner/logo-mark.svg",
  logoRow: "/images/partner/logo-row.png",
  ctaAmbassador: "/images/partner/cta-ambassadors.jpg",
  ctaStoryline: "/images/partner/cta-storylines.jpg",
  ctaSpeaker: "/images/partner/cta-speakers.jpg",
  ctaOrganization: "/images/partner/cta-organization.png",
  wayVenues: "/images/partner/way-venues.svg",
  wayPerks: "/images/partner/way-perks.svg",
  wayResources: "/images/partner/way-resources.svg",
  rewardsGlow: "/images/partner/rewards-glow.svg",
  sealCheck: "/images/partner/seal-check.svg",
  glowAmbassador: "/images/partner/glow-ambassador.svg",
  glowStoryline: "/images/partner/glow-storyline.svg",
  glowSpeaker: "/images/partner/glow-speaker.svg",
} as const;
