const photo = (file: string) => `/images/programs/${file}` as const;
const icon = (file: string) => `/icons/programs/${file}` as const;

export const programPhotos = {
  heroLeft: photo("hero-left.png"),
  heroMid: photo("hero-mid.png"),
  heroRight: photo("hero-right.png"),
  blueZone: photo("blue-zone.png"),
  earth: photo("earth.png"),
  accreditation: photo("accreditation.png"),
  interest: {
    adaptation: photo("interest-adaptation.png"),
    predictiveTech: photo("interest-predictive-tech.png"),
    // Figma MCP 404'd this fill; screens photo is the closest exported topical asset.
    technology: photo("interest-predictive-tech.png"),
    energy: photo("interest-energy.png"),
    mentalHealth: photo("interest-mental-health.png"),
    nutrition: photo("interest-nutrition.png"),
    policy: photo("interest-policy.png"),
    finance: photo("interest-finance.png"),
    immigration: photo("interest-immigration.png"),
    indigenousRights: photo("interest-indigenous-rights.png"),
    climateScience: photo("interest-climate-science.png"),
    insurance: photo("interest-insurance.png"),
    ngo: photo("interest-ngo.png"),
    humanRights: photo("interest-human-rights.png"),
    ai: photo("interest-ai.png"),
  },
  collage: {
    a0417: photo("collage-0417.png"),
    a0418: photo("collage-0418.png"),
    a0419: photo("collage-0419.png"),
    a0420: photo("collage-0420.png"),
    a0421: photo("collage-0421.png"),
    a0614: photo("collage-0614.png"),
    a0615: photo("collage-0615.png"),
    a0616: photo("collage-0616.png"),
    a0617: photo("collage-0617.png"),
    a0618: photo("collage-0618.png"),
    a0619: photo("collage-0619.png"),
    a0620: photo("collage-0620.png"),
  },
  testimonial: {
    coordinator: photo("testimonial-38.png"),
    manager: photo("testimonial-39.png"),
    projectLead: photo("testimonial-40.png"),
  },
  process: {
    step1: photo("process-1.png"),
    step2: photo("process-2.png"),
    step3: photo("process-3.png"),
    step4: photo("process-4.png"),
    step5: photo("process-5.png"),
  },
  aboutProgram: photo("about-program.png"),
} as const;

export const programIcons = {
  speakerX: icon("speaker-x.svg"),
  calendarBlank: icon("calendar-blank.svg"),
  turkeyFlag: icon("turkey-flag.svg"),
  questionMark: icon("question-mark.svg"),
  laptop: icon("laptop.svg"),
  airplaneTakeoff: icon("airplane-takeoff.svg"),
  arrowLeft: icon("arrow-left.svg"),
  arrowLeftHeader: icon("arrow-left-header.svg"),
  arrowClockwise: icon("arrow-clockwise.svg"),
  caretDown: icon("caret-down.svg"),
  plus: icon("plus-alt.svg"),
  excludeLeft: icon("exclude-left.svg"),
  excludeRight: icon("exclude-right.svg"),
  discord: icon("discord.svg"),
  ellipse17: icon("ellipse-17.svg"),
  ellipse18: icon("ellipse-18.svg"),
  ellipse19: icon("ellipse-19.svg"),
  ellipse20: icon("ellipse-20.svg"),
  ellipse21: icon("ellipse-21.svg"),
  ellipse22: icon("ellipse-22.svg"),
  aboutEllipse17: icon("about-ellipse-17.svg"),
  aboutEllipse18: icon("about-ellipse-18.svg"),
  aboutEllipse19: icon("about-ellipse-19.svg"),
  aboutEllipse20: icon("about-ellipse-20.svg"),
  aboutEllipse21: icon("about-ellipse-21.svg"),
  aboutEllipse22: icon("about-ellipse-22.svg"),
  interestBlob: icon("interest-blob.svg"),
} as const;
